name: first-time-setup
run-name: First time setup of the repository

on:
  create:

concurrency:
  group: first-time-setup
  cancel-in-progress: true

jobs:
  first-time-setup:
    if: github.run_number == 1
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove unneeded files
        run: rm -f .github/workflows/first-time-setup.yml .github/FUNDING.yml .github/dependabot.yml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Setup repo'
